
## timing for MDIO interface
#set_max_delay 6.000 -datapath_only -from [get_pins -hier -filter { name =~ */*MDIO_INTERFACE_*/MDIO_OUT_reg/C } ]
set_max_delay 6.000 -datapath_only -from [get_pins -of [get_cells -hierarchical -filter {NAME =~ *MDIO_INTERFACE_*/MDIO_OUT_reg}] -filter {REF_PIN_NAME =~ C}]
#set_max_delay 6.000 -datapath_only -from [get_pins -hier -filter { name =~ */*MDIO_INTERFACE_*/MDIO_TRI_reg/C } ]
set_max_delay 6.000 -datapath_only -from [get_pins -of [get_cells -hierarchical -filter {NAME =~ *MDIO_INTERFACE_*/MDIO_TRI_reg}] -filter {REF_PIN_NAME =~ C}]
#set_false_path -to [get_pins -hier -filter {name =~  *core_resets_i/rst_dly_reg*/PRE}]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *core_resets_i/rst_dly_reg*}] -filter {REF_PIN_NAME =~ PRE}]
#set_property CLOCK_DELAY_GROUP cdg0 [get_nets -of [get_pins -hier -filter {name =~  *core_clocking_i/clk312_buf/O}]]
set_property CLOCK_DELAY_GROUP cdg0 [get_nets -of [get_pins -of [get_cells -hierarchical -filter {NAME =~ *core_clocking_i/clk312_buf}] -filter {REF_PIN_NAME =~ O}]]
#set_property CLOCK_DELAY_GROUP cdg0 [get_nets -of [get_pins -hier -filter {name =~  *core_clocking_i/clk625_buf/O}]]
set_property CLOCK_DELAY_GROUP cdg0 [get_nets -of [get_pins -of [get_cells -hierarchical -filter {NAME =~ *core_clocking_i/clk625_buf}] -filter {REF_PIN_NAME =~ O}]]
  
# false path constraints to async inputs coming directly to synchronizer
#set_false_path -to [get_pins -hier -filter {name =~ *SYNC_*/data_sync*/D }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *SYNC_*/data_sync*}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -to [get_pins -hier -filter {name =~ *SYNC_*/reset_sync*/PRE }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *SYNC_*/reset_sync*}] -filter {REF_PIN_NAME =~ PRE}]

#set_false_path -to [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/*_dom_ch_reg/D }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ */lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/*_dom_ch_reg}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -to [get_pins -hier -filter {name =~  */lvds_transceiver_mw/serdes_1_to_10_ser8_i/rxclk_r_reg/D}]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ */lvds_transceiver_mw/serdes_1_to_10_ser8_i/rxclk_r_reg}] -filter {REF_PIN_NAME =~ D}]

#set_false_path -from [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/loop2[*].ram_ins*/RAM*/CLK }] -to [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/loop0[*].dataout_reg[*]/D }]
set_false_path -from [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/loop2[*].ram_ins*/RAM*}] -filter {REF_PIN_NAME =~ CLK}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/loop0[*].dataout_reg[*]}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -from [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/loop2[*].ram_ins*/RAM*/CLK }] -to [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/loop0[*].dataout_reg[*]/D }]
set_false_path -from [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/loop2[*].ram_ins*/RAM*}] -filter {REF_PIN_NAME =~ CLK}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/loop0[*].dataout_reg[*]}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -from [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/loop2[*].ram_ins*/RAM*/CLK }] -to [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_1_to_10_ser8_i/rxdh*/D }]
set_false_path -from [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/loop2[*].ram_ins*/RAM*}] -filter {REF_PIN_NAME =~ CLK}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_1_to_10_ser8_i/rxdh*}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -to [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_1_to_10_ser8_i/iserdes_m/RST }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_1_to_10_ser8_i/iserdes_m}] -filter {REF_PIN_NAME =~ RST}]
#set_false_path -to [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_1_to_10_ser8_i/iserdes_s/RST }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_1_to_10_ser8_i/iserdes_s}] -filter {REF_PIN_NAME =~ RST}]
#set_false_path -to [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_10_to_1_ser8_i/oserdes_m/RST }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_10_to_1_ser8_i/oserdes_m}] -filter {REF_PIN_NAME =~ RST}]
#set_false_path -to [get_pins -hier -filter {name =~ */*sync_speed_10*/data_sync*/D }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *sync_speed_10*/data_sync*}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -to [get_pins -hier -filter {name =~ */*gen_sync_reset/reset_sync*/PRE }]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *gen_sync_reset/reset_sync*}] -filter {REF_PIN_NAME =~ PRE}]
#set_false_path -to [get_pins -hier -filter { name =~ */*reset_sync_inter*/*sync*/PRE } ]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *reset_sync_inter*/*sync*}] -filter {REF_PIN_NAME =~ PRE}]
#set_false_path -to [get_pins -hier -filter { name =~ */*reset_sync_output_cl*/*sync*/PRE } ]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *reset_sync_output_cl*/*sync*}] -filter {REF_PIN_NAME =~ PRE}]
#set_false_path -to [get_pins -hier -filter { name =~ */*reset_sync_rxclk_div*/*sync*/PRE } ]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *reset_sync_rxclk_div*/*sync*}] -filter {REF_PIN_NAME =~ PRE}]
#set_false_path -to [get_pins -hier -filter { name =~ */*reset_rxclk_div*/*sync*/PRE } ]
set_false_path -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *reset_rxclk_div*/*sync*}] -filter {REF_PIN_NAME =~ PRE}]

#set_false_path -from [get_pins -hier -filter {name =~  */lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/read_enable_reg/C}] -to [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/read_enable_dom_ch_reg/D}]
set_false_path -from [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/read_enable_reg}] -filter {REF_PIN_NAME =~ C}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_10_to_1_ser8_i/gb0/read_enable_dom_ch_reg}] -filter {REF_PIN_NAME =~ D}]
#set_false_path -from [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/read_enable_reg/C}] -to [get_pins -hier -filter {name =~ */lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/read_enabler_reg/D}]
set_false_path -from [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/read_enable_reg}] -filter {REF_PIN_NAME =~ C}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *lvds_transceiver_mw/serdes_1_to_10_ser8_i/gb0/read_enabler_reg}] -filter {REF_PIN_NAME =~ D}]

